export type TechDetail = {
  name: string;
  role: string;
  category: "frontend" | "backend" | "ai" | "database" | "infra" | "api";
};

export type WorkflowStep = {
  step: number;
  title: string;
  description: string;
};

export type Feature = {
  icon: string;
  title: string;
  description: string;
};

export type Challenge = {
  title: string;
  problem: string;
  solution: string;
};

export type Metric = {
  value: string;
  label: string;
  sublabel?: string;
};

export type Project = {
  id: string;
  slug: string;
  number: string;
  title: string;
  subtitle: string;
  tagline: string;
  summary: string;
  problem: string;
  solution: string;
  overview: string[];
  capabilities: string[];
  engineeringDecisions: string[];
  technologies: string[];
  techDetails: TechDetail[];
  workflow: WorkflowStep[];
  features: Feature[];
  challenges: Challenge[];
  results: Metric[];
  roadmap: string[];
  githubUrl?: string;
  demoUrl?: string;
  demonstrates: string;
  modules?: { name: string; description: string }[];
  accent: string;
};

export const projectsData: Project[] = [
  {
    id: "athleteiq",
    slug: "athleteiq",
    number: "01",
    title: "AthleteIQ",
    subtitle: "AI Sports Science RAG Agent",
    tagline: "Sports Science Intelligence for Coaches and Athletes",
    accent: "#22C55E",
    summary:
      "A production-grade sports science assistant that combines retrieval, tool calling, deterministic workload calculations, athlete metric tracking, evaluation, and safety escalation.",
    problem:
      "Coaches and athletes need rapid access to sports science guidance, but general-purpose language models can hallucinate, perform unreliable calculations, and provide unsafe advice in health-adjacent situations.",
    solution:
      "Built a LangGraph ReAct agent with four specialized tools: sports-science retrieval, deterministic ACWR calculation, timestamped athlete metric logging, and three-tier safety escalation.",
    overview: [
      "Sports science is a domain where accuracy is non-negotiable. A coach asking for workload ratios for an injured athlete needs exact calculations, not an approximation. Existing AI tools either hallucinate figures or avoid the question entirely.",
      "AthleteIQ was built to solve this precisely. By separating probabilistic LLM reasoning from deterministic Python math tools, every workload calculation is computed programmatically and verifiable, not generated by a language model.",
      "The system uses LangGraph's ReAct loop to decide which tool to call based on query type: vector retrieval for sports science knowledge, Python math for ACWR, a database writer for metric logging, and an immediate safety escalation bypass when emergency language is detected.",
    ],
    workflow: [
      { step: 1, title: "Coach Query", description: "User asks a sports science question or requests workload calculation." },
      { step: 2, title: "Intent Classification", description: "ReAct agent classifies whether query needs RAG, math tool, metric log, or safety escalation." },
      { step: 3, title: "Emergency Check", description: "Safety router scans for emergency language. If detected, bypasses all retrieval and routes immediately to human escalation." },
      { step: 4, title: "Tool Selection", description: "Agent selects the appropriate tool: ChromaDB RAG, ACWR Python tool, or metric logger." },
      { step: 5, title: "Deterministic Execution", description: "Math tools execute exact Python calculations. RAG retrieves grounded sports science content." },
      { step: 6, title: "Response Synthesis", description: "Agent combines tool outputs into a structured, grounded response." },
      { step: 7, title: "Metric Logging", description: "Athlete metrics are timestamped and persisted to the database for longitudinal tracking." },
    ],
    features: [
      { icon: "🧠", title: "LangGraph ReAct Agent", description: "Multi-step reasoning loop that selects tools based on query intent." },
      { icon: "📚", title: "Sports Science RAG", description: "56-entry ChromaDB knowledge base covering ACWR, HRV, RPE, biomechanics, recovery." },
      { icon: "🧮", title: "Deterministic Math Tools", description: "Python ACWR calculations that bypass LLM for exact, auditable workload ratios." },
      { icon: "🚨", title: "Safety Escalation", description: "Emergency language triggers immediate human escalation, bypassing all retrieval." },
      { icon: "📊", title: "Metric Logging", description: "Timestamped athlete performance data persisted for longitudinal tracking." },
      { icon: "🎯", title: "Hybrid Evaluation", description: "LLM-as-judge scoring combined with rule-based assertions across 20 ground-truth cases." },
    ],
    challenges: [
      {
        title: "Preventing LLM Math Hallucinations",
        problem: "Language models are unreliable for precise numerical calculations like ACWR ratios. A wrong figure in a training load context could injure an athlete.",
        solution: "Routed all workload math to a dedicated Python function tool. The LLM only formats the result — it never generates the numbers.",
      },
      {
        title: "Reliable Safety Escalation",
        problem: "Medical emergencies must be handled immediately without any retrieval delay. A RAG step adds latency that is unacceptable in safety-critical paths.",
        solution: "Implemented a pre-retrieval safety router that pattern-matches emergency language and hard-bypasses all tool calling to produce an immediate human escalation response.",
      },
      {
        title: "Evaluation Without Ground Truth APIs",
        problem: "Evaluating RAG retrieval quality in a domain-specific sports science context is hard without expensive human annotation.",
        solution: "Built a dual evaluation harness: LLM-as-judge for semantic correctness and rule-based assertion for factual claims (ACWR thresholds, HRV ranges), achieving 95% accuracy.",
      },
    ],
    results: [
      { value: "95%", label: "Evaluated Accuracy", sublabel: "Across 20 ground-truth test cases" },
      { value: "85%→95%", label: "Accuracy Improvement", sublabel: "After eval harness + KB refinement" },
      { value: "56", label: "Knowledge Base Entries", sublabel: "Sports science domain coverage" },
      { value: "3-tier", label: "Safety Architecture", sublabel: "RAG → Math → Emergency bypass" },
    ],
    roadmap: [
      "Multi-athlete dashboard",
      "Wearable device integration (HRV, GPS load)",
      "Season periodization planning",
      "Injury prediction scoring",
      "Coach collaboration workspace",
      "Mobile athlete app",
    ],
    capabilities: [
      "Retrieval over a 56-entry sports science knowledge base",
      "Coverage of ACWR, HRV, RPE, overtraining, biomechanics, recovery, and youth athlete safety",
      "ChromaDB semantic retrieval with Hugging Face all-MiniLM-L6-v2 embeddings",
      "Deterministic Python ACWR calculations (Acute:Chronic Workload Ratio)",
      "Timestamped athlete metric logging system",
      "Emergency detection and immediate human escalation bypass",
      "Hybrid evaluation using LLM-as-judge and rule-based checks",
      "Accuracy improvement from 85% to 95% across 20 ground-truth test cases",
    ],
    engineeringDecisions: [
      "The LLM does not perform safety-critical workload mathematics. AthleteIQ routes ACWR calculations to deterministic Python logic.",
      "Bypasses retrieval entirely when a medical emergency is detected, instantly routing to immediate human escalation.",
      "Uses a hybrid eval harness combining LLM-as-judge scoring with rule-based checks for safety-critical questions.",
    ],
    technologies: ["Python", "LangChain LCEL", "LangGraph", "ChromaDB", "Hugging Face", "OpenRouter API", "LLM-as-Judge"],
    techDetails: [
      { name: "Python", role: "Core agent logic, math tools, evaluation harness", category: "backend" },
      { name: "LangGraph", role: "ReAct agent state machine and multi-step reasoning loop", category: "ai" },
      { name: "LangChain LCEL", role: "Tool calling chains and prompt composition", category: "ai" },
      { name: "ChromaDB", role: "Local vector store for sports science knowledge base", category: "database" },
      { name: "Hugging Face", role: "all-MiniLM-L6-v2 embeddings for semantic retrieval", category: "ai" },
      { name: "OpenRouter API", role: "LLM gateway routing to Claude/GPT for agent reasoning", category: "ai" },
      { name: "LLM-as-Judge", role: "Semantic evaluation of retrieval quality and response accuracy", category: "ai" },
    ],
    githubUrl: "https://github.com/Shiva7147/athleteiq",
    demonstrates: "Agent architecture, retrieval engineering, deterministic tools, responsible AI, and measurable evaluation.",
  },
  {
    id: "alpha-receptionist",
    slug: "alpha-receptionist",
    number: "02",
    title: "Alpha Studi0 AI Employee Platform",
    subtitle: "Enterprise AI Employees for Business Automation",
    tagline: "Deploy AI-powered employees that answer phone calls, qualify leads, schedule appointments, and automate customer interactions.",
    accent: "#3B82F6",
    summary:
      "A production real-time AI receptionist platform that handles inbound business calls, understands company context, qualifies leads, schedules appointments, and converts conversations into structured business intelligence.",
    problem:
      "Many small and medium-sized businesses miss calls, lose leads outside working hours, and rely on manual call handling that does not create structured insights.",
    solution:
      "Built a cloud-hosted AI employee platform using Twilio Voice, ElevenLabs for voice synthesis, and Google Gemini for real-time reasoning — supported by a business-specific knowledge layer, automated transcription, lead qualification, scheduling, and a multi-tenant analytics dashboard.",
    overview: [
      "Traditional IVR systems are broken. They frustrate callers with touch-tone menus, offer no real intelligence, and leave businesses with zero insight into what their customers actually need. Answering services are expensive and don't scale.",
      "Alpha Studi0 AI Employee Platform deploys AI-powered employees that understand natural language, know your business deeply, can book appointments directly into Google Calendar, qualify leads against your ideal customer profile, and deliver every conversation as structured analytics.",
      "The core technical challenge was latency. Real-time voice conversations require sub-second response times. The architecture streams audio directly from Twilio through ElevenLabs for voice synthesis and Gemini for reasoning, processing speech without any buffering delay that would make the interaction feel unnatural.",
    ],
    workflow: [
      { step: 1, title: "Customer Calls", description: "Inbound call arrives via Twilio PSTN. WebSocket stream established instantly." },
      { step: 2, title: "Speech Recognition", description: "Real-time audio buffer streaming. ElevenLabs converts speech to text with sub-200ms latency." },
      { step: 3, title: "LLM Reasoning", description: "Google Gemini 2.0 Flash processes the transcript with business context injected as system prompt." },
      { step: 4, title: "Knowledge Retrieval", description: "Business-specific knowledge base queried for company info, pricing, FAQs, and service details." },
      { step: 5, title: "Tool Calling", description: "Agent determines if appointment booking, lead qualification, or CRM update is needed." },
      { step: 6, title: "Calendar Integration", description: "Google Calendar API checks availability and books appointments in real time during the call." },
      { step: 7, title: "Response Generation", description: "ElevenLabs synthesizes natural-sounding voice response streamed back through Twilio." },
      { step: 8, title: "Post-Call Intelligence", description: "Fastify backend processes transcript asynchronously: summarization, lead scoring, CRM write." },
      { step: 9, title: "Analytics Dashboard", description: "Conversation data, lead scores, and call outcomes pushed to Supabase and visualized in dashboard." },
    ],
    features: [
      { icon: "📞", title: "AI Receptionist", description: "Handles inbound calls 24/7 with natural conversation flow and business awareness." },
      { icon: "🎙️", title: "Voice AI", description: "ElevenLabs voice synthesis delivers human-quality audio responses in real time." },
      { icon: "📖", title: "Knowledge Base", description: "Business-specific context injected per call — products, pricing, FAQs, hours, staff." },
      { icon: "🎯", title: "Lead Qualification", description: "AI evaluates caller intent and scores leads against your ideal customer profile." },
      { icon: "📅", title: "Appointment Booking", description: "Google Calendar integration books appointments live during the conversation." },
      { icon: "🗃️", title: "CRM Integration", description: "Call outcomes, contact info, and lead scores written to your CRM automatically." },
      { icon: "📊", title: "Analytics Dashboard", description: "Real-time visualization of call volume, lead quality, and conversation outcomes." },
      { icon: "📝", title: "Call Summaries", description: "AI-generated structured summaries of every conversation delivered post-call." },
      { icon: "🏢", title: "Multi-Tenant SaaS", description: "Row-level security in Supabase isolates each business's data completely." },
    ],
    challenges: [
      {
        title: "Sub-Second Voice Latency",
        problem: "Any perceptible delay in a phone conversation feels broken. Traditional API request/response cycles add 800ms–2s of latency — unacceptable for real-time voice.",
        solution: "Architected a full streaming pipeline: Twilio WebSocket → ElevenLabs streaming STT → Gemini streaming inference → ElevenLabs streaming TTS → Twilio WebSocket. No buffering anywhere in the path.",
      },
      {
        title: "Post-Call Intelligence Without Call Latency",
        problem: "Transcript summarization, lead scoring, and CRM writes are expensive operations. Running them synchronously during a call would add unacceptable latency.",
        solution: "Decoupled the live call pipeline from post-call intelligence. Call ends → transcript queued → Fastify worker picks it up asynchronously → Supabase writes happen with zero impact on call experience.",
      },
      {
        title: "Multi-Tenant Data Isolation",
        problem: "Multiple businesses sharing a database is a security and compliance risk. One misconfigured query could expose another tenant's customer data.",
        solution: "Implemented Supabase Row Level Security (RLS) with per-tenant policies. Every API call passes tenant context, and the database enforces isolation at the query level.",
      },
    ],
    results: [
      { value: "<1s", label: "AI Response Latency", sublabel: "End-to-end voice round-trip" },
      { value: "24/7", label: "Availability", sublabel: "Zero missed calls" },
      { value: "100%", label: "Call Transcription", sublabel: "Every conversation captured" },
      { value: "Multi-tenant", label: "Architecture", sublabel: "Per-business data isolation" },
    ],
    roadmap: [
      "AI Sales Agents",
      "Outbound Calling Campaigns",
      "WhatsApp AI Employee",
      "Email AI Automation",
      "CRM Workflow Builder",
      "White-label Platform",
      "Agent Marketplace",
      "Custom Voice Cloning",
    ],
    capabilities: [
      "Inbound call handling with sub-second latency responses",
      "Real-time AI voice conversations powered by Google Gemini and ElevenLabs",
      "Business-specific knowledge base for company-aware dialogue",
      "Automated lead qualification and transcript summarization",
      "Google Calendar API integration for AI-powered appointment scheduling",
      "Cloud-hosted Fastify backend with Supabase PostgreSQL storage",
      "Customer and conversation analytics dashboard",
      "Multi-tenant SaaS-ready architecture",
    ],
    engineeringDecisions: [
      "Architected sub-second audio response pipeline using real-time streaming buffers between Twilio, ElevenLabs, and Gemini.",
      "Separated call processing from post-call structured intelligence extraction to keep live calls zero-latency.",
      "Persisted all transcriptions and metadata in Supabase PostgreSQL with tenant isolation boundaries enforced at the database level.",
    ],
    technologies: ["Next.js", "React", "TypeScript", "Node.js", "Fastify", "Supabase", "PostgreSQL", "Twilio", "ElevenLabs", "Gemini", "Railway", "OpenRouter", "Google Calendar"],
    techDetails: [
      { name: "Next.js", role: "Frontend dashboard, analytics UI, and business settings interface", category: "frontend" },
      { name: "React", role: "Component-based UI for dashboard and conversation replay", category: "frontend" },
      { name: "TypeScript", role: "End-to-end type safety across frontend and backend services", category: "backend" },
      { name: "Fastify", role: "High-performance Node.js backend for call processing and API layer", category: "backend" },
      { name: "Node.js", role: "Server-side WebSocket handling and real-time audio streaming", category: "backend" },
      { name: "Twilio", role: "PSTN call handling, WebSocket audio streaming, phone number provisioning", category: "api" },
      { name: "ElevenLabs", role: "Real-time speech-to-text and text-to-speech voice synthesis", category: "ai" },
      { name: "Google Gemini", role: "LLM reasoning engine for conversation understanding and response generation", category: "ai" },
      { name: "Supabase", role: "PostgreSQL database with row-level security for multi-tenant data isolation", category: "database" },
      { name: "PostgreSQL", role: "Relational storage for calls, transcripts, leads, and business configs", category: "database" },
      { name: "Google Calendar API", role: "Real-time availability checking and appointment booking during calls", category: "api" },
      { name: "Railway", role: "Cloud deployment platform for Fastify backend with auto-scaling", category: "infra" },
      { name: "OpenRouter", role: "LLM gateway for model fallbacks and cost-optimized routing", category: "ai" },
    ],
    githubUrl: "https://github.com/Shiva7147",
    demonstrates: "Voice AI, low-latency system design, backend orchestration, business automation, and SaaS architecture.",
  },
  {
    id: "alpha-lead-engine",
    slug: "alpha-lead-engine",
    number: "03",
    title: "Alpha Lead Engine",
    subtitle: "AI-Powered Outbound Sales Automation Platform",
    tagline: "From prospect discovery to closed conversation — fully automated, human-reviewed.",
    accent: "#F59E0B",
    summary:
      "A live outbound sales automation platform that discovers leads, qualifies them with AI, generates personalized outreach emails, automates multi-step follow-ups, and classifies replies — reducing manual prospecting to a single reviewable pipeline.",
    problem:
      "Outbound sales teams spend enormous time discovering companies, checking lead quality, researching websites, writing personalized emails, managing follow-ups, and manually reading replies.",
    solution:
      "Designed a unified AI-powered pipeline that moves each prospect from discovery to qualification, personalization, outreach, follow-up, reply classification, and campaign analytics — with a mandatory human review checkpoint before any email is sent.",
    overview: [
      "Sales development is repetitive and expensive. SDRs spend 60-70% of their time on tasks that don't require human judgment: finding companies, checking if they fit the ICP, researching their website, and writing a first email that sounds personal.",
      "Alpha Lead Engine automates exactly those tasks while keeping humans in control of what actually matters: reviewing and approving outreach before it reaches a real prospect.",
      "The system is modular by design. Each of the 6 AI modules has a single responsibility. This makes it testable, replaceable, and improvable independently — a direct contrast to monolithic AI automation systems that fail unpredictably.",
    ],
    workflow: [
      { step: 1, title: "Lead Discovery", description: "Apify scraper finds companies matching target criteria and populates Supabase lead store." },
      { step: 2, title: "ICP Qualification", description: "AI qualification module scores each lead against ideal customer profile criteria." },
      { step: 3, title: "Website Analysis", description: "Company website is scraped and analyzed to extract key sales vectors and pain points." },
      { step: 4, title: "Email Generation", description: "Personalized first-touch email drafted based on website analysis and prospect persona." },
      { step: 5, title: "Human Review", description: "All generated emails shown to human reviewer before any outreach is sent." },
      { step: 6, title: "Outreach Dispatch", description: "Approved emails sent via email API. Campaign tracking begins." },
      { step: 7, title: "Follow-Up Sequences", description: "Day 0, Day 3, Day 7 follow-up emails generated and dispatched automatically." },
      { step: 8, title: "Reply Classification", description: "Incoming replies analyzed and categorized: Interested, Not Now, Not Interested, Unclear." },
      { step: 9, title: "Campaign Analytics", description: "Pipeline metrics, conversion rates, and recommendations displayed in dashboard." },
    ],
    features: [
      { icon: "🔍", title: "Lead Discovery", description: "Apify-powered scraping finds and stores qualified company prospects automatically." },
      { icon: "✅", title: "ICP Qualification", description: "AI scores each lead against your ideal customer profile before spending tokens on outreach." },
      { icon: "🌐", title: "Website Intelligence", description: "Scrapes and synthesizes company sites into actionable sales context." },
      { icon: "✍️", title: "Personalized Emails", description: "AI generates tailored cold emails that reference specific company context." },
      { icon: "👤", title: "Human Review Gate", description: "Mandatory review checkpoint — no email is ever sent without human approval." },
      { icon: "📬", title: "Follow-Up Sequences", description: "Day-based automated follow-up generation (Day 0, 3, 7) without manual scheduling." },
      { icon: "📨", title: "Reply Classification", description: "AI reads and categorizes incoming replies into actionable intent buckets." },
      { icon: "📈", title: "Campaign Analytics", description: "Pipeline performance, open rates, and conversion data in real-time dashboard." },
    ],
    challenges: [
      {
        title: "Ensuring Email Personalization at Scale",
        problem: "Generic cold emails get ignored. But writing truly personalized emails for hundreds of prospects manually is not viable.",
        solution: "Built a two-step pipeline: first scrape and vectorize the company website, then use that context as RAG input to the email generation module. Every email references something real about the specific company.",
      },
      {
        title: "Human Review Without Blocking the Pipeline",
        problem: "Requiring human review for every email risks creating a bottleneck that kills the pipeline's value — especially at volume.",
        solution: "Decoupled review from generation. Emails are generated in batch, queued in Supabase with status 'pending_review', and the reviewer processes them in a dedicated UI whenever convenient — without blocking lead discovery or qualification.",
      },
      {
        title: "Reliable Long-Running Workflow Orchestration",
        problem: "Multi-step workflows with API calls, database writes, scraping, and email dispatch are fragile when built as a single synchronous process.",
        solution: "Used n8n as the workflow orchestration layer, decoupled from the FastAPI application logic. Each workflow step is independently retryable and observable in the n8n dashboard.",
      },
    ],
    results: [
      { value: "6", label: "AI Modules", sublabel: "Single-responsibility, independently replaceable" },
      { value: "100%", label: "Human Review", sublabel: "Before any email is dispatched" },
      { value: "Day 0→7", label: "Follow-Up Automation", sublabel: "Personalized sequence generation" },
      { value: "Live", label: "Production Deployment", sublabel: "Active campaign management" },
    ],
    roadmap: [
      "LinkedIn outreach integration",
      "Enriched data sources (Apollo, Clay)",
      "A/B email testing framework",
      "AI call scheduling",
      "CRM bi-directional sync",
      "Multi-channel sequences",
      "Team collaboration workspace",
    ],
    capabilities: [
      "Automated lead discovery via Apify integration",
      "6 focused single-responsibility AI modules",
      "Human review-before-send workflow guardrail",
      "n8n workflow layer for complex multi-step orchestration",
      "Day-based multi-step follow-up sequencing",
      "Reply intent classification engine",
      "Campaign performance analytics dashboard",
      "Docker containerized production deployment",
    ],
    engineeringDecisions: [
      "Each AI module has a single responsibility, making the system easier to test, maintain, replace, and improve independently.",
      "Implemented a mandatory 'Human Review' checkpoint before email dispatch to guarantee campaign safety.",
      "Decoupled workflow orchestration (n8n) from core application APIs (FastAPI) to handle long-running async tasks smoothly.",
    ],
    technologies: ["Next.js", "FastAPI", "Supabase", "OpenAI API", "n8n", "Apify", "Docker", "REST APIs", "Tailwind CSS"],
    techDetails: [
      { name: "Next.js", role: "Frontend dashboard for campaign management and human review interface", category: "frontend" },
      { name: "FastAPI", role: "Python backend exposing AI module APIs and webhook handlers", category: "backend" },
      { name: "Supabase", role: "Lead store, campaign state, and review queue with real-time subscriptions", category: "database" },
      { name: "OpenAI API", role: "GPT-4 powering qualification, website analysis, and email generation modules", category: "ai" },
      { name: "n8n", role: "Workflow orchestration for multi-step pipeline with independent step retries", category: "infra" },
      { name: "Apify", role: "Web scraping and company data discovery at scale", category: "api" },
      { name: "Docker", role: "Containerized deployment ensuring consistent environments", category: "infra" },
      { name: "Tailwind CSS", role: "Utility-first styling for the campaign management UI", category: "frontend" },
    ],
    githubUrl: "https://github.com/Shiva7147",
    demonstrates: "Applied AI automation, modular AI architecture, workflow orchestration, full-stack product development.",
  },
  {
    id: "reframe",
    slug: "reframe",
    number: "04",
    title: "Reframe",
    subtitle: "Private AI Habit Recovery Web Application",
    tagline: "AI-assisted habit recovery with guaranteed client-side privacy.",
    accent: "#8B5CF6",
    summary:
      "A full-stack AI-assisted behavioral support application designed around personalized assessment, real-time urge interruption, privacy-first storage, offline access, and visual progress tracking.",
    problem:
      "Habit recovery tools often rely on generic advice and require users to share sensitive personal data without meaningful privacy protections.",
    solution:
      "Built a personalized application with a multidimensional weighted assessment, Gemini-powered support, a real-time urge interruption feature, encrypted client-side data handling, anonymous authentication, offline-first PWA support, and progress visualization.",
    overview: [
      "Habit recovery is deeply personal. Users share their triggers, patterns, and struggles with apps that store this data in plaintext on remote servers — often with minimal security guarantees. This is a privacy failure that undermines trust in the tools designed to help.",
      "Reframe was built with a privacy-first guarantee: all personal journal entries and habit data are encrypted in the user's browser using the Web Crypto API before ever touching Firebase Firestore. The server receives only ciphertext it cannot read.",
      "Beyond privacy, the app provides evidence-backed behavioral interventions — urge surfing, cognitive reframing, and progress visualization — powered by Gemini 2.0 Flash with carefully designed prompt boundaries that prevent the AI from overstepping into medical advice.",
    ],
    workflow: [
      { step: 1, title: "Weighted Assessment", description: "User completes multidimensional onboarding assessment. Scores determine personalized plan." },
      { step: 2, title: "PBKDF2 Key Derivation", description: "User passphrase processed through PBKDF2 to derive AES-GCM encryption key. Never leaves device." },
      { step: 3, title: "Client-Side Encryption", description: "All journal entries and habit data encrypted in browser using Web Crypto API before write." },
      { step: 4, title: "Firebase Storage", description: "Only ciphertext reaches Firebase Firestore. Server has zero access to plaintext." },
      { step: 5, title: "Urge Interruption", description: "Real-time micro-interaction tools: breathing timer, cognitive reframes, urge surfing exercises." },
      { step: 6, title: "AI Support", description: "Gemini 2.0 Flash provides evidence-backed behavioral support within defined safety boundaries." },
      { step: 7, title: "Offline Sync", description: "IndexedDB stores data locally when offline. Service worker syncs to Firebase on reconnect." },
      { step: 8, title: "Progress Visualization", description: "Recharts renders streak data, trigger patterns, and recovery milestones from decrypted local data." },
    ],
    features: [
      { icon: "🔒", title: "Client-Side Encryption", description: "AES-GCM 256-bit encryption in the browser. Server receives only ciphertext." },
      { icon: "🧠", title: "AI Support", description: "Gemini 2.0 Flash provides personalized behavioral interventions within safety guardrails." },
      { icon: "⚡", title: "Urge Interruption", description: "Real-time micro-interactions: breathing exercises, cognitive reframes, urge surfing." },
      { icon: "📱", title: "Offline-First PWA", description: "Works without internet. IndexedDB + Service Worker ensures always-available access." },
      { icon: "📊", title: "Progress Tracking", description: "Recharts visualizations of streak data, trigger patterns, and recovery milestones." },
      { icon: "🕵️", title: "Anonymous Auth", description: "Firebase anonymous authentication — no email or personal data required to start." },
    ],
    challenges: [
      {
        title: "Client-Side Encryption Without Performance Degradation",
        problem: "Web Crypto API operations are asynchronous. Encrypting every journal write and decrypting every read needed to be imperceptible to the user.",
        solution: "Implemented a crypto service layer that batches encryption operations and uses IndexedDB as a local cache of decrypted data, only hitting the crypto API on writes and first reads.",
      },
      {
        title: "AI Safety Boundaries for Sensitive Content",
        problem: "Users in recovery may be vulnerable. An AI that oversteps into medical advice or responds carelessly to crisis signals could cause real harm.",
        solution: "Designed system prompt boundaries that explicitly restrict medical diagnosis, mandate referral to professionals when crisis signals are detected, and frame all responses as evidence-backed behavioral support rather than therapy.",
      },
      {
        title: "Offline-First Sync Conflicts",
        problem: "A user making entries offline and online simultaneously can create data conflicts when syncing to Firebase.",
        solution: "Implemented a last-write-wins conflict resolution strategy with client-side timestamps. All entries are append-only journal records, making true conflicts rare and resolvable by merge.",
      },
    ],
    results: [
      { value: "AES-GCM", label: "Encryption Standard", sublabel: "256-bit client-side" },
      { value: "0", label: "Plaintext on Server", sublabel: "Guaranteed by architecture" },
      { value: "PWA", label: "Offline-First", sublabel: "Works without internet" },
      { value: "PBKDF2", label: "Key Derivation", sublabel: "Password-based, device-local" },
    ],
    roadmap: [
      "Peer support community (anonymized)",
      "Therapist integration API",
      "Wearable stress signal integration",
      "Custom trigger pattern analysis",
      "Multi-habit tracking",
      "Progress sharing (privacy-preserving)",
    ],
    capabilities: [
      "Personalized onboarding with multidimensional weighted assessment",
      "Gemini 2.0 Flash contextual behavioral support",
      "Real-time urge interruption micro-interaction experience",
      "Client-side AES-GCM encryption with PBKDF2 key derivation",
      "Anonymous Firebase authentication",
      "Offline-first PWA with automatic background synchronization",
      "Progress visualization using Recharts",
    ],
    engineeringDecisions: [
      "All sensitive assessment and journal data is encrypted on the client using AES-GCM before entering remote storage.",
      "Gemini prompt boundaries explicitly restrict medical diagnosis while providing empathetic, evidence-backed behavioral interventions.",
      "Offline-first indexedDB storage ensures immediate app responsiveness during high-stress urge interruption events.",
    ],
    technologies: ["Next.js", "Gemini 2.0 Flash", "Firebase Firestore", "Tailwind CSS", "Recharts", "Vercel", "Web Crypto API"],
    techDetails: [
      { name: "Next.js", role: "Full-stack PWA framework with App Router and Server Components", category: "frontend" },
      { name: "Gemini 2.0 Flash", role: "Fast, safety-bounded AI for behavioral support and urge interventions", category: "ai" },
      { name: "Firebase Firestore", role: "Remote encrypted storage with real-time sync capabilities", category: "database" },
      { name: "Web Crypto API", role: "Browser-native AES-GCM encryption and PBKDF2 key derivation", category: "backend" },
      { name: "Recharts", role: "Progress visualization: streaks, triggers, and recovery milestones", category: "frontend" },
      { name: "Vercel", role: "Edge deployment with global CDN for fast load times", category: "infra" },
      { name: "Tailwind CSS", role: "Responsive mobile-first UI styling", category: "frontend" },
    ],
    githubUrl: "https://github.com/Shiva7147/reframe-app",
    demonstrates: "Privacy-aware AI product design, full-stack application engineering, secure client-side architecture.",
  },
  {
    id: "smooth-operator",
    slug: "smooth-operator",
    number: "05",
    title: "Smooth Operator",
    subtitle: "AI Dating Profile Coach & RAG Knowledge Engine",
    tagline: "Get real reviewer feedback, backed by AI-powered dating intelligence.",
    accent: "#EC4899",
    summary:
      "A platform connecting men on dating apps with real reviewers who provide personalized voice-note feedback on their profiles, structured across three pricing tiers — backed by a RAG knowledge base and agentic profile analysis engine.",
    problem:
      "Men on dating platforms struggle to get objective, constructive feedback on profile presentation, photo selection, and messaging style — often relying on generic advice that fails to improve match outcomes.",
    solution:
      "Designed the AI layer architecture: a RAG knowledge base of dating archetypes and conversation templates, agent-based profile analysis, and a reviewer feedback retrieval system for personalized coaching delivered as voice notes.",
    overview: [
      "Dating app performance is highly sensitive to profile presentation, photo ordering, bio hooks, and opening message strategy. Yet most men have no objective feedback mechanism — friends are too polite, and generic online advice is too broad to apply.",
      "Smooth Operator solves this with a hybrid approach: real human reviewers who know the domain provide authentic, personalized voice-note feedback, structured and enhanced by an AI knowledge layer that ensures advice is grounded in what actually works.",
      "The AI layer — a RAG knowledge base of dating archetypes, photo composition frameworks, and conversation openers — surfaces relevant patterns and templates that reviewers can reference, making their feedback faster, more consistent, and more actionable.",
    ],
    workflow: [
      { step: 1, title: "Profile Submission", description: "User submits dating app photos, bio, prompts, and messaging examples for review." },
      { step: 2, title: "AI Pre-Analysis", description: "Agentic profile analyzer evaluates bio hooks, photo ordering, and prompt response quality." },
      { step: 3, title: "Archetype Matching", description: "RAG knowledge base matches the profile to relevant dating archetypes and improvement frameworks." },
      { step: 4, title: "Reviewer Assignment", description: "Profile routed to appropriate human reviewer based on tier and specialization." },
      { step: 5, title: "Structured Feedback", description: "Reviewer delivers personalized voice-note feedback structured by the AI analysis layer." },
      { step: 6, title: "Improvement Plan", description: "Actionable improvement plan delivered: photo swap recommendations, bio rewrites, opener templates." },
      { step: 7, title: "Follow-Up Session", description: "Optional follow-up to review implemented changes and measure profile improvement." },
    ],
    features: [
      { icon: "🎙️", title: "Voice-Note Feedback", description: "Real reviewers deliver personalized feedback as voice notes — authentic and actionable." },
      { icon: "🧠", title: "AI Profile Analysis", description: "Agentic analyzer evaluates bio tone, photo composition, and hook effectiveness." },
      { icon: "📚", title: "Dating RAG Knowledge", description: "Vector store of archetypes, frameworks, and conversation templates for consistent advice." },
      { icon: "📸", title: "Photo Strategy", description: "AI-assisted photo ordering and composition analysis based on match-rate data." },
      { icon: "✍️", title: "Bio Optimization", description: "Hook analysis, personality projection, and rewrite recommendations." },
      { icon: "💬", title: "Opener Templates", description: "Conversation starter templates matched to profile style and target demographic." },
    ],
    challenges: [
      {
        title: "Grounding AI Advice in What Actually Works",
        problem: "Generic AI dating advice is often contradictory and not grounded in real match-rate data or platform-specific mechanics.",
        solution: "Built a curated RAG knowledge base of evidence-based frameworks, archetype patterns, and high-performing templates. AI retrieves and applies these rather than generating advice from general training data.",
      },
      {
        title: "Maintaining Authentic Human Reviewer Quality",
        problem: "AI-only feedback risks feeling sterile and impersonal — the opposite of what users need for something as personal as dating.",
        solution: "Kept humans at the center: AI pre-analyzes and structures the brief, but real reviewers deliver the actual feedback as voice notes, preserving authenticity while improving consistency.",
      },
    ],
    results: [
      { value: "3-tier", label: "Service Architecture", sublabel: "Starter, Pro, Elite coaching" },
      { value: "RAG", label: "Knowledge Engine", sublabel: "Archetype-grounded advice" },
      { value: "Voice", label: "Feedback Delivery", sublabel: "Authentic human reviewer notes" },
      { value: "GTM Ready", label: "Go-to-Market", sublabel: "Full collateral and ad briefs" },
    ],
    roadmap: [
      "Mobile app for profile management",
      "Before/after match-rate tracking",
      "Reviewer marketplace expansion",
      "AI-powered opener generator",
      "Video profile analysis",
      "Platform integrations (Hinge, Bumble, Tinder)",
    ],
    capabilities: [
      "RAG knowledge base of dating archetypes, photo selection frameworks, and conversation templates",
      "Agent-based profile analysis engine evaluating bio tone, photo ordering, and prompt hooks",
      "Reviewer feedback retrieval system structuring personalized voice-note delivery",
      "Three-tier pricing and service architecture for custom coaching",
      "Complete go-to-market assets including ad campaign briefs, outreach content, and partnership media kits",
    ],
    engineeringDecisions: [
      "Combined real reviewer voice feedback with RAG dating archetypes so advice remains authentically human while structurally analytical.",
      "Engineered prompt templates that evaluate bio hooks and photo compositions without introducing biased or judgmental tone.",
    ],
    technologies: ["Python", "Next.js", "TypeScript", "OpenAI API", "RAG Architecture", "Supabase", "Tailwind CSS"],
    techDetails: [
      { name: "Python", role: "RAG pipeline, embedding generation, and archetype matching engine", category: "ai" },
      { name: "Next.js", role: "Platform frontend: profile submission, reviewer dashboard, feedback delivery", category: "frontend" },
      { name: "TypeScript", role: "Type-safe API layer and frontend components", category: "backend" },
      { name: "OpenAI API", role: "Profile analysis agent and conversation template generation", category: "ai" },
      { name: "RAG Architecture", role: "Vector store of dating frameworks and archetype patterns for grounded advice", category: "ai" },
      { name: "Supabase", role: "Profile storage, reviewer assignments, and feedback delivery pipeline", category: "database" },
      { name: "Tailwind CSS", role: "Clean, modern UI for profile submission and feedback experience", category: "frontend" },
    ],
    githubUrl: "https://github.com/Shiva7147",
    demonstrates: "Product design, domain RAG architecture, market positioning, and full-stack AI concept execution.",
  },
];
